# Generated by Django 3.2.15 on 2022-09-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranSum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerId', models.IntegerField(verbose_name='CustomerId')),
                ('memberId', models.IntegerField(verbose_name='Member_Id')),
                ('fy', models.CharField(choices=[('2010-2011', '2010-2011'), ('2011-2012', '2011-2012'), ('2012-2013', '2012-2013'), ('2013-2014', '2013-2014'), ('2014-2015', '2014-2015'), ('2015-2016', '2015-2016'), ('2016-2017', '2016-2017'), ('2017-2018', '2017-2018'), ('2018-2019', '2018-2019'), ('2019-2020', '2019-2020'), ('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028'), ('2028-2029', '2028-2029')], max_length=50, verbose_name='FY')),
                ('type', models.CharField(choices=[('Shares', 'Shares'), ('Mutual Funds', 'Mutual Funds'), ('Futures & Options', 'Futures & Options'), ('Day Trading', 'Day Trading'), ('Trading', 'Trading')], max_length=30, verbose_name='Type')),
                ('option', models.CharField(choices=[('O', 'O'), ('A', 'A'), ('S', 'S')], max_length=20)),
                ('scriptId', models.CharField(max_length=200)),
                ('script', models.CharField(max_length=300)),
                ('purchaseDate', models.DateField(verbose_name='PurchaseDate')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=300, verbose_name='Rate')),
                ('value', models.DecimalField(decimal_places=2, max_digits=1000, verbose_name='Value')),
                ('stt', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True, verbose_name='STT')),
                ('other', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True, verbose_name='Oth')),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
